DROP TABLE CTHD;
DROP TABLE HOADON;
DROP TABLE SANPHAM;
DROP TABLE KHACHHANG;
DROP TABLE NHANVIEN;


CREATE TABLE KHACHHANG(
    MAKH CHAR(4) PRIMARY KEY,
    HOTEN NVARCHAR(30),
    DCHI NVARCHAR(50),
    SODT VARCHAR(10),
    NGSINH DATETIME,
    NGDK DATETIME
);

CREATE TABLE NHANVIEN(
    MANV CHAR(4) PRIMARY KEY,
    HOTEN NVARCHAR(40),
    SODT VARCHAR(10),
    NGVL DATETIME
);

CREATE TABLE SANPHAM(
    MASP CHAR(4) PRIMARY KEY,
    TENSP NVARCHAR(30),
    DVT NVARCHAR(20),
    NUOCSX NVARCHAR(30),
    GIABAN MONEY
);

CREATE TABLE HOADON(
    SOHD INT PRIMARY KEY,
    NGHD DATETIME,
    MAKH CHAR(4) REFERENCES KHACHHANG (MAKH),
    MANV CHAR(4) REFERENCES NHANVIEN (MANV),
    TRIGIA MONEY
);

CREATE TABLE CTHD(
    SOHD INT REFERENCES HOADON (SOHD),
    MASP CHAR(4) REFERENCES SANPHAM (MASP),
    SL INT
);

